version: "3.0"
services:
  tetctf:
    container_name: transform2newyear
    build:
      context: .
      dockerfile: ./container/transform2newyear/Dockerfile
    restart: always

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./container/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./container/adminPortal/Dockerfile
    environment:
     - LIFERAY_PORTAL_PERIOD_INSTANCE_PERIOD_PROTOCOL=http
     - LIFERAY_WEB_PERIOD_SERVER_PERIOD_HTTP_PERIOD_PORT=80
    restart: always

