version: "3.8"
services:
  backend:
    build: ./backend
    depends_on: 
      db: 
        condition: service_healthy
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - FLAG=HCMUS-CTF{fake-flag}
  db:
    image: mysql:8.0.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    command: mysqld --default-authentication-plugin=mysql_native_password
    healthcheck:
        test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'db_user', '-pdb_password' ]
        timeout: 20s
        retries: 10